---
version: '3.3'

services:

  roundcubemail:
    image: ghcr.io/kndndrj/pocker-client:latest
    container_name: roundcubemail
    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.example.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.example.com
      - ROUNDCUBEMAIL_SMTP_PORT=465
      - ROUNDCUBEMAIL_LOGO_URL=https://blabla.com/image.png
      - ROUNDCUBEMAIL_PAGE_TITLE=Pocker Mail
      - ROUNDCUBEMAIL_DEFAULT_MAIL_DOMAIN=%d
    # If NOT using Traefik:
    ports:
      - "8080:80"
    # If using Traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`mail.example.com`)"
      - "traefik.http.routers.roundcube.entrypoints=websecure"
      - "traefik.http.routers.roundcube.tls.certresolver=certresolver"
      - "traefik.http.routers.roundcube.service=roundcube"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"

  roundcubedb:
    image: postgres:latest
    container_name: roundcubedb
    restart: unless-stopped
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=roundcube
