#!/bin/sh

USAGE="Usage: $0 <user> [password]
If password is not defined, you will be prompted for it."

if [ -z "$1" ]; then
    echo "$USAGE"
    exit 1
fi


###################################
## PASSWORD VALIDATION           ##
###################################
USERNAME="$1"
PASSWORD="$2"

if ! (grep -q "^$USERNAME:" /etc/passwd); then
    echo "error: user $USERNAME doesn't exist"
    exit 1
fi

# Ask for password here (if not already provided), so we can exit before doing anything
if [ -z "$PASSWORD" ]; then
    printf "current password for user $USERNAME: "
    stty -echo
    read PASSWORD
    stty echo
    echo
fi

# Read the existing password from /etc/shadow
SHADOW="$(getent shadow $USERNAME)"
HASH="$(echo "$SHADOW" | cut -d ":" -f 2)"
FORMAT="$(echo "$HASH" | cut -d "$" -f 2)"
SALT="$(echo "$HASH" | cut -d "$" -f 3)"

if [ "$FORMAT" != "6" ]; then
    echo "error: unsupported hashing algorithm of current password: \"\$$OLDFORMAT\$\""
    exit 1
fi

# Validate the password
if [ "$(openssl passwd -6 -salt $SALT $PASSWORD)" != "$HASH" ]; then
    echo "error: wrong password!"
    exit 1
fi


###################################
## REMOVE USER RECORDS           ##
###################################
TEMP="$(mktemp)"

# /etc/passwd
if (grep -q "^$USERNAME:" /etc/passwd); then
    sed "/^$USERNAME:/d" /etc/passwd > $TEMP
    cat "$TEMP" > /etc/passwd
fi

# /etc/group - remove
if (grep -q "^$USERNAME:" /etc/group); then
    sed "/^$USERNAME:/d" /etc/group > $TEMP
    cat "$TEMP" > /etc/group
fi

# /etc/group - remove from mail group
if (grep -q "^mail:x:.*$USERNAME" /etc/group); then

    # handle comma
    REMOVE_STRING="$USERNAME"
    if (grep -q "^mail:x:.*,$USERNAME" /etc/group); then
        REMOVE_STRING=",$USERNAME"
    elif (grep -q "^mail:x:.*$USERNAME," /etc/group); then
        REMOVE_STRING="$USERNAME,"
    fi

    sed "/mail:x:/ s/$REMOVE_STRING//g" /etc/group > $TEMP
    cat "$TEMP" > /etc/group
fi

# /etc/shadow
if (grep -q "^$USERNAME:" /etc/shadow); then
    sed "/^$USERNAME:/d" /etc/shadow > $TEMP
    cat "$TEMP" > /etc/shadow
fi

# /etc/gshadow
if (grep -q "^$USERNAME:" /etc/gshadow); then
    sed "/^$USERNAME:/d" /etc/gshadow > $TEMP
    cat "$TEMP" > /etc/gshadow
fi

###################################
## HOME AND MAIL DIRECTORIES     ##
###################################
rm -rf "/home/$USERNAME" "/var/mail/$USERNAME"
