#!/bin/sh

USAGE="Usage: $0 <from> <to>"

if [ -z "$2" ]; then
    echo "$USAGE"
    exit 1
fi

###################################
## VARIABLES                     ##
###################################
FROM="$1"
TO="$2"

# Check if user which you alias to exists
if ! (grep -q "^$TO:" /etc/passwd); then
    echo "error: user $TO doesn't exist"
    exit 1
fi

# create a backup
BACKUP="$(mktemp)"
cat /etc/aliases > "$BACKUP"

# If alias group already exists
if (grep -q "^$FROM:" /etc/aliases); then

    # Check if user is already in alias group
    if (grep -Eq "^$FROM:.*(|\s|,)$TO($|\s|,)" /etc/aliases); then
        echo "info: user is already in $FROM alias group"
        exit 0
    fi

    TEMP="$(mktemp)"
    sed "/^$FROM:/ s/$/,$TO/g" /etc/aliases > "$TEMP"
    cat "$TEMP" > /etc/aliases
    rm "$TEMP"
else
    # If alias group doesn't exist
    echo "$FROM: $TO" >> /etc/aliases
fi

# Generate new aliases and check for errors
RESPONSE=$(newaliases -f /etc/aliases 2>&1)
if [ -n "$RESPONSE" ]; then
    echo "error: $RESPONSE"
    echo "error: rolling back"
    cat "$BACKUP" > /etc/aliases
    rm "$BACKUP"
    exit 1
fi

echo "info: created a new alias $FROM: $TO"
