#!/bin/sh

# Route stderr to stdout
exec 2>&1

SOCKET="/var/spool/postfix/spamass/spamass.sock"

# Create socket directory with spamass-milter as an owner
mkdir -p "$(dirname "$SOCKET")"
chown spamass-milter "$(dirname "$SOCKET")"

# Change permissions of the socket after it has been created
change_permissions() {
    sleep 1
    chmod 0660 "$SOCKET"
    chown postfix:postfix "$SOCKET"
}
change_permissions &

# default user: spamass-milter
# ignore 127.0.0.1
exec /usr/sbin/spamass-milter -p "$SOCKET" -u spamass-milter -i 127.0.0.1
