---

name: Docker Build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Short Commit SHA
        id: sha_short
        run: echo "value=$(echo ${{ github.sha }} | head -c 10)" >> "$GITHUB_OUTPUT"

      - name: Get Major version
        id: major_version
        run: echo "value=$(ver=${{ github.ref_name }}; echo ${ver%.*})" >> "$GITHUB_OUTPUT"

      - name: Build and Push Base Image
        uses: docker/build-push-action@v3
        with:
          context: "."
          target: base
          push: ${{ github.event_name != 'pull_request' }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ steps.major_version.outputs.value }}
            ghcr.io/${{ github.repository }}:${{ steps.sha_short.outputs.value }}

      - name: Build and Push Dashboard Image
        uses: docker/build-push-action@v3
        with:
          context: "."
          target: dashboard
          push: ${{ github.event_name != 'pull_request' }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
          tags: |
            ghcr.io/${{ github.repository }}:latest-dashboard
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-dashboard
            ghcr.io/${{ github.repository }}:${{ steps.major_version.outputs.value }}-dashboard
            ghcr.io/${{ github.repository }}:${{ steps.sha_short.outputs.value }}-dashboard
